add ability to load python classes (blueprints, etc) directly from git (#332)
* add ability to load blueprints directly from git

* disable git clones in tests

tests work properly locally but fail on CircleCI:

```
======================================================================
ERROR: test_package_sources_in_config (stacker.tests.test_context.TestContext)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/stacker/stacker/tests/test_context.py", line 181, in test_package_sources_in_config
    context.load_config(config)
  File "/home/ubuntu/stacker/stacker/context.py", line 98, in load_config
    processor.get_package_sources(sources=sources)
  File "/home/ubuntu/stacker/stacker/util.py", line 508, in get_package_sources
    self.fetch_git_package(config=config)
  File "/home/ubuntu/stacker/stacker/util.py", line 542, in fetch_git_package
    with Repo.clone_from(config['uri'], tmp_repo_path) as repo:
AttributeError: __exit__
-------------------- >> begin captured logging << --------------------
git.cmd: DEBUG: Popen(['git', 'clone', '-v', 'https://github.com/remind101/stacker_blueprints.git', '/tmp/stackerXAY6EB/https___github.com_remind101_stacker_blueprints-1.0.0'], cwd=/home/ubuntu/stacker, universal_newlines=False, shell=None)
git.repo.base: DEBUG: Cmd(['git', 'clone', '-v', 'https://github.com/remind101/stacker_blueprints.git', '/tmp/stackerXAY6EB/https___github.com_remind101_stacker_blueprints-1.0.0'])'s unused stdout:
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_SourceProcessor_operation (stacker.tests.test_util.TestUtil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/stacker/stacker/tests/test_util.py", line 140, in test_SourceProcessor_operation
    'paths': ['stacker_blueprints']}]}
  File "/home/ubuntu/stacker/stacker/util.py", line 508, in get_package_sources
    self.fetch_git_package(config=config)
  File "/home/ubuntu/stacker/stacker/util.py", line 542, in fetch_git_package
    with Repo.clone_from(config['uri'], tmp_repo_path) as repo:
AttributeError: __exit__
-------------------- >> begin captured logging << --------------------
git.cmd: DEBUG: Popen(['git', 'clone', '-v', 'https://github.com/remind101/stacker_blueprints.git', '/tmp/stackerIiqSk_/https___github.com_remind101_stacker_blueprints-1.0.0'], cwd=/home/ubuntu/stacker, universal_newlines=False, shell=None)
git.repo.base: DEBUG: Cmd(['git', 'clone', '-v', 'https://github.com/remind101/stacker_blueprints.git', '/tmp/stackerIiqSk_/https___github.com_remind101_stacker_blueprints-1.0.0'])'s unused stdout:
--------------------- >> end captured logging << ---------------------
```

* updated per feedback